### ISSUE TITLE
VC funding column in Retro PGF Round 3

### ISSUE THREAD

**Issue by tjayrush** [growthepie/gtp-frontend#49]
Excellent site. So useful. Thanks.

I appreciate the VC Funding column in your table. For me, it mattered, and I used it when selecting projects that I thought deserved funding. (Not that I excluded based on this, but it mattered.)

May I suggest that instead of putting "Unknown" for projects that you don't know, you use the words, "None known." Or even better yet, allow projects to explicitly tell you that they've received no VC funding, nor do they intend to. That also would have been very helpful.

Cheers.

**Comment by manishiwa** [comment]
@tjayrush, we really appreciate your feedback on our [RetroPGF3 Tracker](https://growthepie.xyz/optimism-retropgf-3). It's really nice to hear that it was useful! 

We made some changes last week and updated the column to enhance clarity.

![image](https://github.com/growthepie/gtp-frontend/assets/6618044/216d1033-828d-45f5-b8b3-4d3b88b1f179)

The column now includes three distinct categories:

- **[USD Value Raised]** - This shows the reported amount of VC funding a project has received.
- **"Unknown / DYOR"** (Do Your Own Research) - This label is used for projects where the VC funding status is not clear or publicly available.
- **"No VC Funding"** - This explicitly indicates projects that have not received any venture capital funding mostly from projects that have reached out to us.

We plan on continuing to track future RPGF rounds — please join us on [Discord](https://discord.gg/pKzYwm7h) or reach out to us on [Twitter/X](https://www.twitter.com/growthepie_eth) if you have any other feedback or suggestions!

Cheers!
